### PR TITLE
New search layout and copy for staging demo

### PR DESCRIPTION
**Pull request by emilyville**
I think this is good enough for the demo (maybe?), there are some hacks and if we want to skip it for tomorrow and not merge this, that's fine.

this page will still needs 
- to limit the amount of featured jobs. I added a overflow hidden in the css and commented around the block that it's only for the demo and should be deleted.
- to make the job search load in the same layout. I commented out results for now - so search on this page is hidden. 
- the footer looks weird on this screenshot but not in real life. 

screencapture-localhost-3000-job-seekers-search_jobs-1459402185597

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@cfeeney-va there are a bunch of broken tests here. any chance you have bandwidth to dig into these?

**Comment by cfeeney-va** [comment]
yes :)  assigning task to myself

**Comment by emilyville** [comment]
If this one is still in progress, merge #252 instead

**Comment by emilyville** [comment]
I'm closing this. We can bring it back some day.

**Pull request closed without merging**
