### PR TITLE
Remove unused environment variables

### PR DESCRIPTION
**Pull request by ayaleloehr**

### CODE REVIEW

**Comment by cfeeney-va** [comment]
looks like some of these are still in code (but not used)...can we remove from there too?

**Comment by jkassemi** [comment]
The SAML provider is linked to from the `/job-seekers/for_job_seekers` page. Though I don't see any public references to it, it's tested by `spec/features/job_search_spec.rb`.

Are those specs hitting anything that's still in use somehow?

**Comment by ayaleloehr** [comment]
Had moved on from VEC and clearly left this hanging...The `/job-seekers/for_job_seekers` page is no longer served out of this repo, so anything only linked to it is no longer relevant. As for that spec, it's likely left in there by mistake. I had a [massive PR](https://github.com/department-of-veterans-affairs/veterans-employment-center/pull/293) a while back that took out a lot of functionality and it's likely I just missed it. but would have to actually go back and check. Doesn't feel like the highest priority to me at this time, however. Let me know if there is a date you need this done by @jkassemi or a pressing reason to bump it up the queue?

**Comment by jkassemi** [comment]
Definitely not high priority. No deadline or reason to bump it up in the queue just yet. I expect when we merge into platform-api we'll address a few cleanup tasks including this one.

**Comment by patrickvinograd** [comment]
Closing, ENV vars removed by #380. README.md could stand some cleanup at some point.

**Pull request closed without merging**
