### PR TITLE
Update Coursera language

### PR DESCRIPTION
**Pull request by ayaleloehr**

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Including an image so you can more easily see what this change does. The Coursera box is now one line longer than the LinkedIn box. Thoughts @gnakm ?

cc @bethpotts since she wrote the copy. 

screen shot 2016-02-25 at 11 28 02 pm

**Comment by gnakm** [comment]
You're talking about the height of the card/ button, right? I need to redesign the layout of this page in general and @emilyville and I talked about character limits for cards because of this issue. Thanks for reminding us. Will be useful for roadrunner!

**Comment by gnakm** [comment]
related to #90

**Comment by ayaleloehr** [comment]
talked with @gnakm and going to close this PR without merging because a larger redesign is coming that enforces character limits on cards.

**Pull request closed without merging**
