### PR TITLE
Move to ruby 2.3 and update dependencies

### PR DESCRIPTION
**Pull request by ayaleloehr**
Also updates README to be more accurate and cleaner.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@cfeeney-va please make sure you can get this working locally before merging, as it involves updating a lot of dependencies and thus could have broken many things.

**Comment by ayaleloehr** [comment]
This change breaks tests locally for me. DO NOT MERGE UNTIL RESOLVED.  

When I have ruby-version at 2.2.3, all tests pass. When I move ruby-version to 2.3.0, tests fail with the repeated error
```
Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/veterans-employment-center/skills-translator/get_common_skills"
     # /Users/vacoyalela/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /Users/vacoyalela/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
```
Travis passes with ruby-version at 2.3.0, so this could be a local issue to my machine, but I want to verify before merging.

**Comment by cfeeney-va** [comment]
Seems to work for me:

Finished in 1 minute 47.71 seconds (files took 6.65 seconds to load)
240 examples, 0 failures, 10 pending

Let me know if I can help/you want to discuss!

**Comment by cfeeney-va** [comment]
LGTM @ayaleloehr

**Comment by ayaleloehr** [comment]
Issue resolved. Was a problem with environment variables in my local setup. Merging.

**Pull request merged**
