### PR TITLE
Remove profile bank

### PR DESCRIPTION
**Pull request by ayaleloehr**
And changes search_jobs URLs to search-jobs.

### CODE REVIEW

**Comment by cfeeney-va** [comment]
Hey Alex, is there a wets-website pull request that goes along with this?  Was doing something unrelated and saw the following on the job-seeker page:
"Build your résumé and public profile so employers can find you"
We should probably up this and make sure it's the only reference if you haven't already.

**Comment by ayaleloehr** [comment]
@cfeeney-va Yep, there is! You can view it here: https://github.com/department-of-veterans-affairs/vets-website/pull/2241

Thanks for checking!!

**Comment by cfeeney-va** [comment]
LGTM

PIcky detail: 
app/views/veterans/new.html.erb
The Veterans Employment Center (VEC) can help you enter your information, which can then be downloaded into a civilian or federal résumé.

I think this sentence is a little awkward; I'd just write something like:
The Veterans Employment Center (VEC) can help you build a civilian or federal résumé.

However, feel free to merge without making this change as it is pretty insignificant :)

**Comment by ayaleloehr** [comment]
Not picky, accurate!

Merging.

**Comment by emilyville** [comment]
Nice change @cfeeney-va!

**Pull request merged**
