### PR TITLE
Use USA Standard error states

### PR DESCRIPTION
**Pull request by bshyong**
This branch implements USA Standard error states as shown below.

Resume builder:
screen shot 2016-08-17 at 5 58 26 pm

Skills Translator is an Angular app...
screen shot 2016-08-17 at 7 27 11 pm

### CODE REVIEW

**Comment by bshyong** [comment]
Addresses https://github.com/department-of-veterans-affairs/vets-website/issues/2686

**Comment by bshyong** [comment]
@crwallace This fixes the error states on the resume builder 100% and fixes the basic required states on the skills translator. 

The skills translator is going to take some more time as the code is pretty confusing. It's an Angular.js app and a little difficult to discover how it interfaces with the backend. I will spend some more time looking into it tomorrow.

**Comment by bshyong** [comment]
Update: @crwallace this is ready for review. Updated error state to handle the Angular app component in the skills translator. Skills Translator and Resume Builder are now all using USA Standard Web Error states.

See below:
screen shot 2016-08-18 at 1 07 06 pm

**Comment by crwallace** [comment]
This LGTM!

**Pull request merged**
