### PR TITLE
Fix skills init

### LINKED ISSUE #344: Migrations won't run from start
Removal of the MigrationHelper module in 24be4ad prevents the migrations from running, since it's referenced in several migrations to assist with loading skills translator models from CSVs:

[`db/migrate/20151014183437_load_skills_translator_model.rb`](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/db/migrate/20151014183437_load_skills_translator_model.rb)
[`db/migrate/20151015183437_create_dummy_skills_translator.rb`](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/db/migrate/20151015183437_create_dummy_skills_translator.rb)
[`db/migrate/20151210212237_add_default_skills.rb`](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/db/migrate/20151210212237_add_default_skills.rb)

This looks like functionality that's available now from the [db:seed_skills task](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/lib/tasks/seed_skills.rake) - should the migrations be consolidated?

### PR DESCRIPTION
**Pull request by cfeeney-va**
Fixes #344 

Adds skills and skill/MOC links to db:seed

Comments out old migrations used to add/modify skills

Kind of a hack-y way to fix it, but it works.  Tested by setting up VEC locally from scratch.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@cfeeney-va glad you were able to get this working so quickly. Since we have version control, I think deleting the code instead of commenting it out would be best. Thoughts?

**Comment by cfeeney-va** [comment]
@ayaleloehr deleting the entire file, or just the code within it?
I *think* deleting the file would be ok, but I know the timestamps are saved in the migrations table and I don't know enough about rails to know if not having the file but having the timestamp would cause issues.  I'd have to do some research on that.  Leaving them seems like the best bet, but I can look into it if you want!

**Comment by cfeeney-va** [comment]
per conversation with alex, deleting commented code in file

**Comment by jkassemi** [comment]
Thanks @cfeeney-va! 

I have records in `military_operations` and `skills_for_military_occupations` along with a single `skills_translator_models` record. Is there a good smoke test you can recommend that will quickly validate that the data import contains everything that's expected?

**Comment by jkassemi** [comment]
@cfeeney-va - can you also squash those commits?

**Comment by ayaleloehr** [comment]
@jkassemi you can squash commits via GitHub UI now!  If you click the big green Merge Pull Request button, it then comes up with a "confirm and squash commits" button that does it for you.

**Comment by cfeeney-va** [comment]
You should end up with:
36 records in the skills_for_military_occupations table,
22368 records in military_occupations and all should have a source of 'DOD_ODB'

**Comment by jkassemi** [comment]
Thanks @cfeeney-va!

**Pull request merged**
