### PR TITLE
Fixing tests when no static content

### PR DESCRIPTION
**Pull request by ayaleloehr**
33 tests were broken from when I removed the static content. Thus far this PR fixes 19 of them. Of the remaining 14 broken tests, there are really only two types: 

- [ ] (1 failure) "logging out when logged in, an employer can log out". Currently when logging out as an employer, it takes you back to the home page. Since we won't be having a home page in this repo anymore, I believe it should instead take you to `/employers`. So that would involve 1) a change to where it directs the user after logout and 2) a change to the test to have the end of [this line](https://github.com/department-of-veterans-affairs/veterans-employment-center/blob/master/spec/features/employer_setup_spec.rb#L276) become `expect(page).to have_content 'Employers'`

- [ ] (13 failures) The "JobSearch /search_jobs" tests all try to `visit for_job_seekers_path`, which no longer exists.  When I tried changing `for_job_seekers_path` to `search_jobs_path` the tests were trying to execute an API call to do the job search, since this is what the `search_jobs_path` does. We will either need to stub this call or find some other workaround now that the `for_job_seekers_path` is not in this repo and thus cannot be used in the unit test. 

@cfeeney-va would love some help on this tomorrow if you have bandwidth. If so, let's sit down together to discuss!

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@cfeeney-va PTAL.

Fixed the last tests by just adding in a stub of a job-seekers page. This stub won't actually be used in production, but since it seems from [this issue](https://github.com/department-of-veterans-affairs/vets-website/issues/1581) that we will be reworking the search page anyways, this was a faster fix than editing all the search page tests just to edit them again later this week.

**Comment by ayaleloehr** [comment]
@cfeeney-va and I talked in person on this. She was rightfully concerned that it is not ideal to have the job_seekers static page in here when it's not actually used. Because the job_search page is likely about to get a large edit in the next week, however, it's not worth changing these tests yet, as they will need to be edited again then.  Issue #247 has been created for this and needs to be closed prior to the C&E launch.

**Comment by cfeeney-va** [comment]
Thanks Alex!  LGTM

**Comment by emilyville** [comment]
Seems like this is done, @cfeeney-va ?

**Comment by cfeeney-va** [comment]
yup, is merged and should be closed :)

**Pull request merged**
