### PR TITLE
Removes ShareThis button.js file

### LINKED ISSUE #40: "Please specify Sharethis publisher key info" message emitted in debug console
<a href="https://github.com/jjtswan"></img></a> **Issue by [jjtswan](https://github.com/jjtswan)**
_Tuesday Nov 10, 2015 at 02:21 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/299_

----

OSX Chrome

1. https://staging.vets.gov/veterans-employment-center/for_job_seekers/#
2. Open debug console (apple+option+i)

I get the following console log:

image

### PR DESCRIPTION
**Pull request by MarinaMartin**
Fixes #40 

Please review @ayaleloehr

### CODE REVIEW

**Comment by MarinaMartin** [comment]
Erp hang on, broke a test.

**Comment by ayaleloehr** [comment]
Was that button.js file also used in line 12 of /app/assets/javascripts/search/search_jobs.js via `stButtons.locateElements();`?

If so, does this break any functionality there?

**Comment by ayaleloehr** [comment]
@MarinaMartin also line 5 of /app/views/search/_search_header.html.erb 

I believe you can just remove that line (and the line in the previous Github comment above).

**Comment by MarinaMartin** [comment]
@ayaleloehr Awesome catches. I search for other ShareThis references (stWidget, stLight, etc.) but didn't find any.

**Comment by ayaleloehr** [comment]
LGTM

**Pull request merged**
