### PR TITLE
Switching to Puma

### PR DESCRIPTION
**Pull request by ayaleloehr**
Hoping to get a code review from @awong-dev , as I know he'll be excited about this change. If you don't have time or think someone else should be assigned, just let me know!

### CODE REVIEW

**Comment by MarinaMartin** [comment]
You should specify the version number of the puma gem.

**Comment by awong-dev** [comment]
Yay!  Following on to @MarinaMartin's comment.... what's the story for the version numbers in general in this Gemfile?  Most of the gems have no version restriction.

On the flipside...what's the benefit of a version restriction if we have a gemlock file?

**Comment by MarinaMartin** [comment]
The benefit of versions is it stops it from auto updating to a new version on deploy and breaking unexpected things. Which happened to me once in my last life and was horrible.

**Comment by awong-dev** [comment]
Cool. So we should lock the major version number then, not the exact version number?

**Comment by awong-dev** [comment]
@ayaleloehr ^^^ That's in your court. I think lock the major version of puma (using whatever the right ruby syntax is for that...which I think is a ~, but may be a >...should read up on current best practices) before checking in this CL.

Then we can add major versions for other stuff.

**Comment by ayaleloehr** [comment]
Following the guidance from [here](http://rubygems.rubyforge.org/rubygems-update/Gem/Version.html), went with the ~> syntax. Can I get a LGTM from @awong-dev or @MarinaMartin ?

Will create an issue to edit the rest of this Gemfile with version numbers, but that is out of scope for this PR.

**Comment by awong-dev** [comment]
LGTM!

**Pull request merged**
