### PR TITLE
Replace trashcan icons with delete link

### LINKED ISSUE #81: Trashcan icon does not appear in IE
<a href="https://github.com/MarinaMartin"></img></a> **Issue by [MarinaMartin](https://github.com/MarinaMartin)**
_Tuesday Dec 22, 2015 at 01:22 GMT_
_Originally opened as https://github.com/department-of-veterans-affairs/veterans-employment-center-private-pre-01-27-2015/issues/450_

----

The trashcan icon to delete a skill within the resume creation page does not appear in Internet Explorer (I think 11).

### PR DESCRIPTION
**Pull request by cfeeney-va**
Fixes #81 

Replaced trashcan icon with "- delete" link.  Per conversation in #81, this is preferred to icons and is better for accessibility.  I also like the consistency with the "+ Add Experience" links.

### CODE REVIEW

**Comment by ayaleloehr** [comment]
@emilyville @gnakm can one of you give an opinion on this?  Change is seen below so it's quicker for you to look at.  This feels like awkward UX to me. Not sure I'm a big fan of the `-` and might make the font size smaller?  Is `delete` the right word or should it be `remove` or something else?  I'm out of my element here though, so going to defer to one of you. 

screen shot 2016-02-25 at 10 23 55 pm

**Comment by gnakm** [comment]
Christine worked on something similar today and our verdict was that the word_remove_ makes more sense than delete. Let's do _remove skill_ and take away the "-"
We should try to keep everything on the form consistent.

**Comment by cfeeney-va** [comment]
Changing to "remove"

**Comment by cfeeney-va** [comment]
I don't actually think it looks that bad... (although def feel free to disagree!)

screen shot 2016-02-26 at 10 58 53 am

**Comment by emilyville** [comment]
Agreed! Looks good and will work consistently :)

**Comment by ayaleloehr** [comment]
LGTM.

**Comment by MarinaMartin** [comment]
I also like what @cfeeney-va did!

**Pull request merged**
