### PR TITLE
Removed 'View Candidate button"

### PR DESCRIPTION
**Pull request by gnakm**
This is a solution for #55 
Please review @ayaleloehr !

### CODE REVIEW

**Comment by ayaleloehr** [comment]
Whats the `app/views/static_pages/Find Results` file?  I don't think that should be in there. 

It also seems there are some tests tied to this card being there that we will need to edit.

**Comment by gnakm** [comment]
I do not know what "app/views/static_pages/Find Results" is...

**Comment by cfeeney-va** [comment]
@gnakm if you need someone to review the tests with you let me know!

**Comment by gnakm** [comment]
@cfeeney-va yes can you review this please?

**Comment by gnakm** [comment]
@ayaleloehr Take 2. Please review again!

**Comment by ayaleloehr** [comment]
LGTM

**Pull request merged**
